import { productImage } from "@/lib/products/site-images";
import type { ProductPage } from "@/lib/products/types";

export const gasChlorinationProduct = {
  slug: "gas-chlorination",
  metadata: {
    title:
      "Gas chlorinator India|Gas Chlorination|Chemical dosing|chlorine dosing",
    description:
      "Industrial Devices is a leading Chlorination System manufacturers in India. Chlorine Dosing System Manufacturers India, Chlorine Vaporizer, Gas Chlorinator India, Chlorination System Manufacturers.",
  },
  seoHeadings: [
    { level: 1, text: "Gas Chlorinator Manufacturers in India" },
    { level: 2, text: "Chlorinator Manufacturers India" },
    { level: 3, text: "Chlorine Dosing System Manufacturers India" },
    { level: 4, text: "Chlorine Vaporizer" },
    { level: 5, text: "Gas Chlorinator India" },
    { level: 6, text: "Chlorination System Manufacturers" },
  ],
  sectionHeadingId: "gas-chlorinator-models",
  sectionTitle: "Gas chlorinator",
  sectionTitleHighlight: "models",
  models: [
    {
      id: "cylinder-tonner",
      heading: "Cylinder Mounted Models",
      imageSrc: productImage("cylinder-mounted-chlorinator.jpg"),
      imageAlt: "Cylinder mounted chlorinator",
      descriptionPoints: [
        "Reliable & Efficient Chlorination Solutions",
        "The INDEVICE Cylinder Mounted Chlorinators are designed to deliver versatile, high-quality, and cost-effective chlorine dosing solutions. These vacuum-operated systems ensure safe, reliable, and efficient chlorine feed for a wide range of water treatment applications.",
        "Mounted directly onto chlorine cylinders or ton containers using a robust yoke clamp connection, the system provides a secure and leak-proof installation for enhanced operational safety.",
        "Each chlorinator is equipped with essential components, including:",
        "Chlorine Flow Meter",
        "Flow Control Valve",
        "Pressure Relief Valve",
        "The system features an exclusively designed vacuum regulator that operates only when vacuum is generated by the injector. It automatically shuts off whenever the vacuum pressure falls below the specified limit, ensuring maximum safety and preventing chlorine leakage.",
      ],
      specs: [
        { label: "Capacity", value: "100 g/hr to 10 kg/hr" },
        {
          label: "Applications",
          value:
            "Ideal for a wide range of water treatment needs, including: Swimming Pools, Drinking Water Treatment, Small-Capacity Water Treatment Plants, Potable Water Treatment in Power Plants",
        },
      ],
    },
    {
      id: "floor-mounted",
      heading: "Floor Mounted Models",
      imageSrc: productImage("gas-chlorination-system-with-vaporiser.jpg"),
      imageAlt: "Floor mounted vacuum chlorinator",
      descriptionPoints: [
        "High-Performance Chlorination Systems for Demanding Applications",
        "The INDEVICE Floor Mounted Chlorinators are advanced, vacuum-operated, solution feed systems engineered for reliable and precise chlorine dosing across a wide range of water treatment applications.",
        "Designed for efficiency and operational safety, these systems incorporate high-quality components, including:",
        "Chlorine Pressure & Vacuum Gauges",
        "Reliable Vacuum Regulator",
        "Accurate Flow Meter",
        "Precision Flow Control Valve",
        "Efficient Differential Regulator",
        "Injector",
        "Drain Valve",
        "Non-Return Valve",
        "Built with a simple yet advanced design philosophy, the chlorinator minimizes maintenance requirements while ensuring long-term performance and reliability. All major components are conveniently accessible from the rear of the cabinet, enabling easy periodic inspection and maintenance.",
        "Each chlorinator is factory pre-assembled and thoroughly tested under simulated operating conditions, reducing installation time and costs while ensuring a smooth and hassle-free start-up.",
        "The system can be offered with Proportionate Dosing Feature for automatic dosing either with input from On-line Chlorine Analyzer or Flow Meter.",
      ],
      specs: [
        { label: "Capacity", value: "100 g/hr to 1000 kg/hr" },
        {
          label: "Applications",
          value:
            "Suitable for diverse water treatment applications, including: Drinking Water Treatment, Effluent Treatment Plants (ETP), Sewage Treatment Plants (STP), Cooling Water Treatment, Raw Water Treatment in Power Plants",
        },
      ],
    },
    {
      id: "wall-mounted",
      heading: "Wall Mounted Chlorinators",
      imageSrc: productImage("wall-mounted-chlorinator.png"),
      imageAlt: "Wall mounted chlorinator",
      descriptionPoints: [
        "Compact & Reliable Chlorination Solutions",
        "The INDEVICE Wall Mounted Chlorinators are compact, vacuum-operated, solution feed systems designed for accurate and reliable chlorine dosing in smaller to medium-capacity water treatment applications.",
        "Engineered for dependable performance and ease of operation, the system incorporates high-quality components, including Chlorine Pressure & Vacuum Gauges, Vacuum Regulator, Flow Meter, Flow Control Valve, Injector, Drain Valve and Non-Return Valve",
        "With a robust and efficient design, the wall-mounted chlorinator ensures safe operation, precise dosing, and low maintenance, making it an ideal solution for continuous water disinfection requirements.",
      ],
      specs: [
        { label: "Capacity", value: "100 g/hr to 5 kg/hr" },
        {
          label: "Applications",
          value:
            "Ideal for a variety of water treatment applications, including: Drinking Water Treatment, Water Treatment Plants, Potable Water Treatment in Power Plants",
        },
      ],
    },
  ],
} satisfies ProductPage;
