import { parseProductSpec } from "@/lib/products/parse-spec";
import { legacyUpload } from "@/lib/products/site-images";
import type { ProductPage } from "@/lib/products/types";

const cylinderBullets = [
  "For capacities from 100gms/hr to 10 kgs/hr.",
  "MOC: FRP Cabinet, HDPE, PVC, PTFE, Hastalloy C internals.",
  "Suitable for: Swimming pool, Drinking Water, smaller capacity Water treatment plant and Potable water treatment in power plant.",
] as const;

const floorBullets = [
  "For capacities from 100 gms/hr to 1000 kgs/hr.",
  "Auto Flow Proportionate feature (Optional).",
  "MOC: FRP Cabinet, HDPE, PVC, PTFE, Hastalloy C internals.",
  "Suitable for : Drinking water, effluent treatment, sewage treatment, cooling water and raw water treatment in power plant.",
] as const;

const wallBullets = [
  "For capacities from 100 gms/hrto 5kgs/hr.",
  "MOC:FRP Cabinet, HDPE, PVC, PTFE, Hastalloy C internals.",
  "Suitable for : Drinking water, Water treatment plant, Potable water treatment in power plant.",
] as const;

export const gasChlorinationProduct = {
  slug: "gas-chlorination",
  metadata: {
    title:
      "Gas chlorinator India|Gas Chlorination|Chemical dosing|chlorine dosing",
    description:
      "Industrial Devices is a leading Chlorination System manufacturers in India. Chlorine Dosing System Manufacturers India, Chlorine Vaporizer, Gas Chlorinator India, Chlorination System Manufacturers.",
  },
  seoHeadings: [
    { level: 1, text: "Gas Chlorinator Manufacturers in India" },
    { level: 2, text: "Chlorinator Manufacturers India" },
    { level: 3, text: "Chlorine Dosing System Manufacturers India" },
    { level: 4, text: "Chlorine Vaporizer" },
    { level: 5, text: "Gas Chlorinator India" },
    { level: 6, text: "Chlorination System Manufacturers" },
  ],
  sectionHeadingId: "gas-chlorinator-models",
  sectionTitle: "Gas chlorinator",
  sectionTitleHighlight: "models",
  models: [
    {
      id: "cylinder-tonner",
      heading: "Cylinder Mounted Models",
      imageSrc: legacyUpload("Cylinder%20mounted%20chlorinators.jpg"),
      imageAlt: "Cylinder mounted chlorinator",
      descriptionPoints: [
        "The indichlor CM Cylinder mounted chlorinators are versatile and of high quality.",
        "They are low cost solution feed units, which are vacuum operated.",
        "The chlorinator is mounted on the cylinder or a ton container by means of a yoke clamp connection, which offers a leak proof joining.",
        "The chlorine flow meter, flow control valve, pressure relief valve are part of the chlorinator.",
        "The vacuum regulator is of an exclusive design, which opens only when the vacuum is generated by the injector & it closes automatically when the vacuum pressure goes below the specified limit.",
      ],
      specs: cylinderBullets.map(parseProductSpec),
    },
    {
      id: "floor-mounted",
      heading: "Floor Mounted Models",
      imageSrc: legacyUpload("Floor%20Mounted%20chlorinators.jpg"),
      imageAlt: "Floor mounted vacuum chlorinator",
      descriptionPoints: [
        "This is a floor mounted, vacuum operated, solution feed type chlorinator. It incorporates chlorine pressure and vacuum gauges, reliable vacuum regulator, and an accurate flow meter, a precise flow control valve, an effective differential regulator, an injector, drain valve and a non return valve.",
        "The simple yet advanced design of the various components reduce the maintenance to a bare minimum. All the components are easily accessible from the rear of the cabinet for periodic Inspection and Maintenance.",
        "The Chlorinator is pre-assembled and is fully tested under simulated operating condition. This saves time and money during installation and helps towards a smooth start-up.",
      ],
      specs: floorBullets.map(parseProductSpec),
    },
    {
      id: "wall-mounted",
      heading: "Wall Mounted Chlorinators",
      imageSrc: legacyUpload("Wall%20Mounted%20chlorinators.png"),
      imageAlt: "Wall mounted chlorinator",
      descriptionPoints: [
        "This is a Wall mounted, vacuum operated, solution feed type.",
        "It incorporates chlorine pressure and vacuum gauges, reliable vacuum regulator, and an accurate flow meter, a precise flow control valve, an injector, drain valve and a non return valve.",
      ],
      specs: wallBullets.map(parseProductSpec),
    },
  ],
} satisfies ProductPage;
