export type ClientListEntry = {
  serial: number;
  client: string;
  capacity: string;
  year: string;
};

export type ClientListSection = {
  id: string;
  title: string;
  entries: readonly ClientListEntry[];
};

export type ClientListCatalog = {
  id: string;
  title: string;
  description: string;
  pdf: string;
  sections: readonly ClientListSection[];
};

export const wtpStpClientSections = [
  {
    id: "wtp-stp-chlorination",
    title: "WTP & STP Chlorination",
    entries: [
      {
        serial: 1,
        client: "50 MLD STP KADABEESHANAHALLI, BWSSB, BENGALURU, THROUGH M/S TOSHIBA WATER SOLUTIONS",
        capacity: "2X25 KG/HR WITH LEAK ABSORPTION SYSTEM",
        year: "Under execution",
      },
      {
        serial: 2,
        client: "Deogarh-Reamal through M/S. UNIVERSAL MEP PROJECTS & ENGINEERING SERVICES LTD (M/s VOLTAS LTD)",
        capacity: "2x5 kg/hr pre and 2x3 kg/hr post Chlorination System with Leak Absorption System",
        year: "Under Commissioning",
      },
      {
        serial: 3,
        client: "Sambalpur through M/S. UNIVERSAL MEP PROJECTS & ENGINEERING SERVICES LTD (M/s VOLTAS LTD)",
        capacity: "2x2 kg/hr pre and 2x1 kg/hr post Chlorination System with Leak Absorption System",
        year: "Under Commissioning",
      },
      {
        serial: 4,
        client: "20 MLD STP at Alwar, Rajasthan through M/s Geo Miller & Co. Ltd., New Delhi",
        capacity: "2x5 kg/hr chlorination system",
        year: "Under Commissioning",
      },
      {
        serial: 5,
        client: "M/s. WPIL, kolkata",
        capacity: "2x5 kg/hr Chlorination System for Madhya Pradesh Jal Nigam (WSS Panna)",
        year: "Under Commissioning",
      },
      {
        serial: 6,
        client: "1.5 MLS STP Sujangarh through M/s Anprash Projects Pvt Ltd",
        capacity: "2x500 gms/hr Chlorination System (2 Set)",
        year: "Under Commissioning",
      },
      {
        serial: 7,
        client: "Chandanhandi through M/s GVPR Engineers Ltd",
        capacity: "2x3 pre and 2x2 post Chlorination System with Leak Absorption System",
        year: "Under Commissioning",
      },
      {
        serial: 8,
        client: "24 MLD WTP Puthera, Dhawarra WSS Sijwaha through Ms/ Sri SCL Infratech Ltd",
        capacity: "2x10 kg/hr Pre and 2x5 kg/hr Post Chlorination System",
        year: "Under Commissioning",
      },
      {
        serial: 9,
        client: "22 MLD STP Malerkotla, Punjab through M/s Gharpure Engineeering & Constructions Pvt Ltd",
        capacity: "2x12 kg/hr Chlorination System with Leak Absorption System",
        year: "Under Commissioning",
      },
      {
        serial: 10,
        client: "33 MLD and 7.5 MLD Dahod Smart City, Gujarat through M/s Endress+Hauser India Pvt Ltd",
        capacity: "2x10 kg/hr Pre and 2x5 kg/hr Post Chlorination System with Leak Absorption System for 33 MLD and 2x3 kg/hr Pre and 2x1 kg/hr Post Chlorination System with Leak Absorption sysetm for 7.5 MLD",
        year: "2023 & 2024",
      },
      {
        serial: 11,
        client: "Nayagarh through M/s GVPR Engineers Ltd",
        capacity: "2x12 pre and 2x10 post Chlorination System with Leak Absorption System",
        year: "2026",
      },
      {
        serial: 12,
        client: "100 MLD STP MYLASANDRA, BWSSB, BENGALURU, THROUGH M/S TOSHIBA WATER SOLUTIONS",
        capacity: "4X35 KG/HR WITH LEAK ABSORPTION SYSTEM",
        year: "2025",
      },
      {
        serial: 13,
        client: "Dhenkanal through M/S. UNIVERSAL MEP PROJECTS & ENGINEERING SERVICES LTD (M/s VOLTAS LTD)",
        capacity: "2x12 kg/hr pre and 2x10 kg/hr post Chlorination System with Leak Absorption System",
        year: "2025",
      },
      {
        serial: 14,
        client: "Nabarangpur through M/s GVPR Engineers Ltd",
        capacity: "2x10 pre and 2x6 post Chlorination System with Leak Absorption System",
        year: "2025",
      },
      {
        serial: 15,
        client: "65 MLD Pullivendula through M/s Megha Engineering & Infrastructures Ltd",
        capacity: "4x10 kg/hr pre and post Chlorination System",
        year: "2025",
      },
      {
        serial: 16,
        client: "15 MLD STP Muzzafarpur, Bihar through M/s Toshiba Water Solutions Pvt ltd",
        capacity: "2x15 kg/hr Chlorination System with Leak Absorption System",
        year: "2025",
      },
      {
        serial: 17,
        client: "8 MLD STP Agartala, West Tripura through M/s MecGale Pneumatics Pvt Ltd",
        capacity: "2x5 kg/hr Chlorination system with Leak Absorption System",
        year: "2025",
      },
      {
        serial: 18,
        client: "through M/s AARUNYA",
        capacity: "2x5 kg/hr Chlorination System",
        year: "2025",
      },
      {
        serial: 19,
        client: "Deogarh-Barkote through M/S. UNIVERSAL MEP PROJECTS & ENGINEERING SERVICES LTD (M/s VOLTAS LTD)",
        capacity: "2x5 kg/hr pre and 2x3 kg/hr post Chlorination System with Leak Absorption System",
        year: "2024",
      },
      {
        serial: 20,
        client: "Puri through M/S. UNIVERSAL MEP PROJECTS & ENGINEERING SERVICES LTD (M/s VOLTAS LTD)",
        capacity: "2x5 kg/hr pre and 2x3 kg/hr post Chlorination System with Leak Absorption System",
        year: "2024",
      },
      {
        serial: 21,
        client: "Chhapi JJM II through GCKC Projects and Works Pvt Ltd",
        capacity: "4x3 kg/hr pre and post Chlorination System",
        year: "2024",
      },
      {
        serial: 22,
        client: "Kuaramunda-Nuagaon through M/s Universal MEP Projects & Engineering Service Ltd",
        capacity: "2x10 kg/hr Pre and 2x5 kg/hr Post Chlorination System with Leak Absorption System",
        year: "2024",
      },
      {
        serial: 23,
        client: "M/s. VA Tech Wabag",
        capacity: "4x30 kg/hr pre and 4x15 kg/hr post chlorination system with Leak Absorption System for 55 MGD WTP at Uttarpara, KMDA.",
        year: "2024",
      },
      {
        serial: 24,
        client: "WTP at GT Halli, BWSSB Bangalore, through M/s. Mega Engineering & Infrastructure Ltd, Hyderabad",
        capacity: "2x25 kg/hr chlorination system with Leak absorption system",
        year: "2024",
      },
      {
        serial: 25,
        client: "STP at GT Halli, BWSSB Bangalore, through M/s. Mega Engineering & Infrastructure Ltd, Hyderabad",
        capacity: "2x 10 kg/hr chlorination system with Leak absorption system",
        year: "2024",
      },
      {
        serial: 26,
        client: "21 MLD STP Ghazipur through M/s Prescient Flow Control India Pvt Ltd",
        capacity: "2x5 kg/hr Chlorination system with Leak Absorption System",
        year: "2024",
      },
      {
        serial: 27,
        client: "through M/s Subhash Infr Engineers Pvt Ltd",
        capacity: "2x20 kg/hr Chlorination System",
        year: "2024",
      },
      {
        serial: 28,
        client: "42 MLD Dhone through M/s Megha Engineering & Infrastructures Ltd",
        capacity: "4x6 kg/hr pre and post Chlorination System",
        year: "2024",
      },
      {
        serial: 29,
        client: "69 MLD WTP Jhilo through M/s GVPR Engineers Ltd",
        capacity: "2x15 kg/hr pre and 2x10 kg/hr post Chlorination System with Leak Absorption System",
        year: "2024",
      },
      {
        serial: 30,
        client: "53 MLD WTP Sala through M/s GVPR Engineers Ltd",
        capacity: "2x15 kg/hr pre and 2x5 kg/hr post Chlorination System with Leak Absorption System",
        year: "2024",
      },
      {
        serial: 31,
        client: "Dibrugarh through M/s WPIL Ltd",
        capacity: "2x10 kg/hr Chlorination System with Leak Absorption System",
        year: "2024",
      },
      {
        serial: 32,
        client: "Sahawali and Kidwai Nagar through M/s Lahoty Buildcon Ltd",
        capacity: "2x10 kg/hr Chlorination System with Leak Absorption System for Sahawali and Kidwai Nagar",
        year: "2024",
      },
      {
        serial: 33,
        client: "Budhana Town STP through M/s GA Infra Pvt Ltd",
        capacity: "2x5 kg/hr Chlorination system with Leak Absorption System",
        year: "2024",
      },
      {
        serial: 34,
        client: "Jhagadia through M/s Aarti Industries Ltd",
        capacity: "2x3 kg/hr Chlorination System with Leak Absorption System",
        year: "2024",
      },
      {
        serial: 35,
        client: "Coimbatore WTP through M/s V.A. Tech Wabag Ltd",
        capacity: "3x30 kg/hr Chlorination System with Leak Absorption System",
        year: "2023",
      },
      {
        serial: 36,
        client: "6 MLD STP Ayodhya through M/s Jiya Engineering & Construction",
        capacity: "2x3 kg/hr Chlorination System with Leak Absorption System",
        year: "2023",
      },
      {
        serial: 37,
        client: "90 MLD Delawas STP, Pratap Nagar, Jaipur through M/s Khilari Infrastructure Pvt Ltd",
        capacity: "2x20 kg/hr Chlorination System with Leak Absorption System",
        year: "2023",
      },
      {
        serial: 38,
        client: "60 MLD WTP Mirzapur, Uttar Pradesh through M/s Gannon Dunkerley & Co. Ltd.",
        capacity: "2x10 kg/hr pre and 2x5 kg/hr post Chlorination System with Leak Absorption System",
        year: "2023",
      },
      {
        serial: 39,
        client: "28 MLD STP Haldwani through M/s Aquatech Solutions Pvt Ltd",
        capacity: "2x6 kg/hr Chlorination System with Leak Absorptoin System",
        year: "2023",
      },
      {
        serial: 40,
        client: "7 MLD STP Puttenahalli, Yelahanka, Bangalore through M/s Sepcon Systems Pvt Ltd",
        capacity: "2x3 kg/hr Chlorination System with Leak Absorption System",
        year: "2023",
      },
      {
        serial: 41,
        client: "2.3 MLD and 3.5 MLD Telangana through M/s Solpro Automation Systems",
        capacity: "4x1 kg/hr Pre & Post Chlorination System for 2.3 MLD and 4x1 kg/hr Pre & Post Chlorination System for 3.5 MLD",
        year: "2022",
      },
      {
        serial: 42,
        client: "Sujangarh through M/s Anprash Projects",
        capacity: "2x1 kg/hr and 2x3 kg/hr Chlorination System",
        year: "2022",
      },
      {
        serial: 43,
        client: "12.5 MLD STP Tonca, Panjim, Goa through M/s SFC Environmental Technologies Pvt Ltd",
        capacity: "2x5 kg/hr Chlorination system with Leak Absorption System",
        year: "2022",
      },
      {
        serial: 44,
        client: "Shahjahanpur through M/s Rosa Power Supply Co. Ltd.",
        capacity: "2x15 kg/hr Chlorination System",
        year: "2022",
      },
      {
        serial: 45,
        client: "Delawas STP Jaipur through M/s Khilari Infrastructure Pvt Ltd",
        capacity: "2x30 kg/hr Chlorination System with Leak Absorption System",
        year: "2022",
      },
      {
        serial: 46,
        client: "200 MLD WTP at Akelgarh UWSS Kota through M/s Offshore Infrastructure Ltd",
        capacity: "2x50 kg/hr post chlorination system",
        year: "2022",
      },
      {
        serial: 47,
        client: "8 MLD STP at Nagaur, Rajasthan through M/s Geo Miller & Co. Ltd., New Delhi",
        capacity: "2x3 kg/hr chlorination system",
        year: "2022",
      },
      {
        serial: 48,
        client: "150 MLD at K& C Valley STP , BWSSB Bangalore, through M/s VA Tech Wabag Ltd.",
        capacity: "4 x 40 kg/hr chlorination system with Leak absorption system",
        year: "2022",
      },
      {
        serial: 49,
        client: "NCC LTD",
        capacity: "2X3 kg/hr pre and 2x3 kg/hr post chlorination system for RWSS SUNDARGARH (MANDIRA), ODISHA",
        year: "2021",
      },
      {
        serial: 50,
        client: "25 MLD WTP at Bidhangarh, KMC, Kolkata through M/s. VA Tech Wabag Limited, Chennai",
        capacity: "2 Nos. of 40 kg/hr and 2 Nos. of 10 kg/hr Chlorination system with Leak absorption system",
        year: "2021",
      },
      {
        serial: 51,
        client: "M/s. NCC Ltd, Hyderabad",
        capacity: "2x6 kg/hr pre and 2x3 kg/hr post for Keonjhar and 8x3 kg/hr chlorination system for Anandpur, Jajpur, Sundergarh Mandira and Lunipara Water Supply Schemes.",
        year: "2021",
      },
      {
        serial: 52,
        client: "LC INFRA PROJECTS PVT LTD",
        capacity: "2x6 kg/hr chlorination system with las for 28 mld stp Bhubaneshwar and 2x2 kg/hr chlorination system with las for 8 mld stp Bhubaneshwar",
        year: "2021",
      },
      {
        serial: 53,
        client: "NCC LTD",
        capacity: "2X3 kg/hr pre and 2x3 kg/hr post chlorination system for RWSS JAJPUR (ODISHA)",
        year: "2021",
      },
      {
        serial: 54,
        client: "NCC LTD",
        capacity: "2X3 kg/hr pre and 2x3 kg/hr post chlorination system for RWSS ANANDPUR (ODISHA)",
        year: "2021",
      },
      {
        serial: 55,
        client: "NCC LTD",
        capacity: "2X6 kg/hr pre and 2x3 kg/hr post chlorination system for RWSS KEONJHAR (ODISHA)",
        year: "2020",
      },
      {
        serial: 56,
        client: "NCC LTD",
        capacity: "2X3 kg/hr pre and 2x3 kg/hr post chlorination system for RWSS SUNDARGARH (LAUNIPARA) - ODISHA",
        year: "2020",
      },
      {
        serial: 57,
        client: "35 MLD STP at Algaram, BWSSB Bangalore through M/s Ayyappa Infra Project Pvt. Ltd.",
        capacity: "2x 10 kg/hr chlorination system with Leak absorption system",
        year: "2020",
      },
      {
        serial: 58,
        client: "5 MLD STP at Sarakki , BWSSB Bangalore through M/s Ayyappa Infra Project Pvt. Ltd.",
        capacity: "2x 3 kg/hr chlorination system with Leak absorption system",
        year: "2020",
      },
      {
        serial: 59,
        client: "5 MLD STP at Chikabegur, BWSSB Bangalore through M/s Ayyappa Infra Project Pvt. Ltd.",
        capacity: "2x 3 kg/hr chlorination system with Leak absorption system",
        year: "2020",
      },
      {
        serial: 60,
        client: "SAIL BHILAI Steel Plant through M/s VOLTAS LTD",
        capacity: "3x10 kg/hr Chlorination System with Leak Absorption System",
        year: "2020",
      },
      {
        serial: 61,
        client: "225 MLD WTP Agra WSS through M/s VOLTAS LTD (UP Jal Nigam)",
        capacity: "6x50 kg/hr pre and 4x40 kg/hr post Chlorination System with Leak Absorption System",
        year: "2020",
      },
      {
        serial: 62,
        client: "40 MLD STP at Doddabelle, BWSSB Bangalore through M/s Triveni Engineering & Infrastructure Ltd.",
        capacity: "2x 15 kg/hr chlorination system with Leak absorption system",
        year: "2020",
      },
      {
        serial: 63,
        client: "M/s. WPIL, kolkata",
        capacity: "2x2 kg/hr Chlorination System for Madhya Pradesh Jal Nigam (WSS Panna)",
        year: "2019",
      },
      {
        serial: 64,
        client: "M/s. SMC Infrastructure Pvt Ltd",
        capacity: "2x20 kg/hr chlorination system for WSS Likhubula River, Republic of Malawi, SA",
        year: "2019",
      },
      {
        serial: 65,
        client: "M/s. WPIL, Kolkata",
        capacity: "2x2 kg/hr Chlorination System for Madhya Pradesh Jal Nigam (WSS Badonkalan)",
        year: "2019",
      },
      {
        serial: 66,
        client: "Khatra WSS, West Bengal through M/s NCC Ltd (PHED West Bengal)",
        capacity: "3x10 kg/hr pre and 3x3 kg/hr post Chlorination System with Leak Absorption System for WTP. 2x1 kg/hr kg/hr Chlorination System for OHR'S",
        year: "2018",
      },
      {
        serial: 67,
        client: "Bankura WSS through M/s NCC Ltd (PHED West Bengal)",
        capacity: "3x15 kg/hr pre and 3x10 kg/hr post Chlorination System with Leak Absorption system for WTP. 2x1 kg/hr Chlorination System for OHRS.",
        year: "2018",
      },
      {
        serial: 68,
        client: "BWSSB Bellandur STP , Bangalore through M/s M/s VA Tech Wabag Ltd.",
        capacity: "2x 40 kg/hr chlorination system with Leak absorption system",
        year: "2018",
      },
      {
        serial: 69,
        client: "Water supply system Udasar Napasan Bikaner Beachwal through M/s. Shiv Bhandar Construction Company, Rajasthan",
        capacity: "2 Nos. of 1 kg/hr Chlorination system",
        year: "2018",
      },
      {
        serial: 70,
        client: "90 MLD WTP at Avanthipuram, Nalagonda, TDWSP, Telangana through M/s. Equis Infra, Hyderabad.",
        capacity: "2 Nos. of 15 kg/hr pre and 2 Nos. of 5 kg/hr Post chlorination system",
        year: "2018",
      },
      {
        serial: 71,
        client: "60 MLD WTP at Dharma Sagar, Warrangal, through M/s. Salient Projects Pvt. Ltd., Hyderabad (Telangana)",
        capacity: "2 Nos. of 15 kg/hr pre and 2 Nos. of 6 kg/hr post chlorination system",
        year: "2018",
      },
      {
        serial: 72,
        client: "20 MLD WTP at Dharma Sagar, Warrangal, through M/s. Salient Projects Pvt. Ltd., Hyderabad (Telangana)",
        capacity: "2 Nos. of 5 kg/hr pre and 2 Nos. of 2 kg/hr post chlorination system",
        year: "2018",
      },
      {
        serial: 73,
        client: "40 MLD WTP at Antharam Rangareddy, TDWSP, Telangana through M/s. SMC Infrastructure Pvt. Ltd., Thane (Maharashtra)",
        capacity: "15 kg/hr pre and 5 kg/hr post chlorination systemn",
        year: "2018",
      },
      {
        serial: 74,
        client: "100 MLD WTP at Sangareddy, TDWSP, Telangana Drinking Water Project through M/s. Xlant Infra, Hyderabad",
        capacity: "2 Nos. of 25 kg/hr and 2 Nos. of 10 kg/hr Chlorination system",
        year: "2018",
      },
      {
        serial: 75,
        client: "100 MLD WTP at Peddapalli, Karimnagar, Telangana through M/s. Xlant Infra, Hyderabad.",
        capacity: "2 Nos. of 40 kg/hr and 2 Nos. of 15 kg/hr chlorination system",
        year: "2018",
      },
      {
        serial: 76,
        client: "20 MLD STP at Nagasandra, BWSSB, Bangalore through M/s. GECPL Enviro, Pune.",
        capacity: "2 Nos. of 15 kg/hr chlorination system with leak absorption system",
        year: "2018",
      },
      {
        serial: 77,
        client: "20 MLD STP at Horamavu, Agara, BWSSB, Bangalore through M/s. GECPL, Pune",
        capacity: "2 Nos. of 15 kg/hr chlorination system with leak absorption system",
        year: "2018",
      },
      {
        serial: 78,
        client: "35 MLD WTP through Sai Enviro Engineers Pvt. Ltd., Telangana",
        capacity: "2 Nos. of 10 kg/hr and 2 Nos. of 5 kg/hr chlorination system with Leak Absorption system",
        year: "2018",
      },
      {
        serial: 79,
        client: "120 MLD WTP at Agaraharam, TDWSP, Karimnagar, Telangana through M/s. Sai Enviro Engineers Pvt. Ltd.",
        capacity: "2 Nos. of 40 kg/hr and 2 Nos. of 20 kg/hr chlorination system",
        year: "2018",
      },
      {
        serial: 80,
        client: "32 MLD WTP at Bhupalapally, TDWSP, Telangana through M/s. Dundhubi Infra, Hyderabad",
        capacity: "2 Nos. of 10 kg/hr and 2 Nos. of 5 kg/hr chlorination system with Leak Absorption system",
        year: "2018",
      },
      {
        serial: 81,
        client: "145 MLD WTP at Dabba Village, Ibrahimpatnam, Telangana through M/s. Dundhubi Infra, Hyderabad",
        capacity: "2 Nos. of 40 kg/hr and 2 Nos. of 20 kg/hr chlorination system",
        year: "2018",
      },
      {
        serial: 82,
        client: "50 MLD WTP at Kamalgiri Hills, Khammam, Telangana through M/s. NCC Ltd., Hyderabad",
        capacity: "2 Nos. of 12 kg/hr and 2 Nos. of 5 kg/hr chlorination system",
        year: "2018",
      },
      {
        serial: 83,
        client: "90 MLD WTP at Jeelacheruvu, TDWSP, Telangana through M/s. Machine Tools Aids (India), Hyderabad",
        capacity: "2 Nos. of 20 kg/hr for pre and 2 Nos. of 10 kg/hr for post chlorination system",
        year: "2018",
      },
      {
        serial: 84,
        client: "Chambal Bhilwara Water Supply Project through M/s Megha Engineering & Infrastructure Ltd, Hyderabad",
        capacity: "8x7 kg/hr and 10x2 kg/hr chlorination and leak absorption system",
        year: "2018",
      },
      {
        serial: 85,
        client: "Chambal Bhilwara Water Supply Phase-II Cluster Scheme of 150 villages, Kotri Tehsil, Rajasthan through M/s Megha Engineering & Infrastructure Ltd, Hyderabad",
        capacity: "4x2 kg/hr and 4x5 kg/hr chlorination and leak absorption system",
        year: "2018",
      },
      {
        serial: 86,
        client: "144 MLD UPJN Agra through M/s VOLTAS LTD (UP Jal Nigam)",
        capacity: "2x40 kg/hr pre and 2x60 kg/hr post Chlorination System with Leak Absorption System",
        year: "2018",
      },
      {
        serial: 87,
        client: "Jawai pipe line WS Project Pkg-II, Cluster Project-II, PHED Pali, Rajasthan, through M/s Megha Engineering & Infrastructure Ltd, Hyderabad",
        capacity: "2 Nos. of 10 kg/hr and 2 Nos. of 5 kg/hr chlorination and leak absorption system",
        year: "2017",
      },
      {
        serial: 88,
        client: "BWSSB K & C Valley(S1C), Bangalore through M/s M/s VA Tech Wabag Ltd.",
        capacity: "2x 30 kg/hr chlorination system with Leak absorption system",
        year: "2017",
      },
      {
        serial: 89,
        client: "20 MLD STP at Madhial,Dharwad (Karnataka) through M/s Gondwana Engineers Ltd.",
        capacity: "1x 5 kg/hr chlorination system",
        year: "2017",
      },
      {
        serial: 90,
        client: "WTP at Thoothukudi, Tamil Nadu through M/s. Eco Protection Engineers Pvt. Ltd. (L&T), Chennai",
        capacity: "2 Nos. of 10 kg/hr Chlorination system",
        year: "2017",
      },
      {
        serial: 91,
        client: "WTP at Palani Municipality, Tamil Nadu through M/s. Eco Protection Engineers Pvt. Ltd., Chennai",
        capacity: "1 No. of 5 kg/hr Chlorination system",
        year: "2017",
      },
      {
        serial: 92,
        client: "STP at Rajkot Municipal Corporation, Gujarat through M/s. Eco Protections Engineers Pvt. Ltd., Chennai",
        capacity: "2 Nos. of 5 kg/hr Chlorination system",
        year: "2017",
      },
      {
        serial: 93,
        client: "STP at Bidar, Karnataka through M/s. Megha Engineering & Infrastructure Ltd.",
        capacity: "2 Nos. of 15 kg/hr chlorination system",
        year: "2017",
      },
      {
        serial: 94,
        client: "70 MLD WTP at Jurela Dam, Mehaboob Nagar, Telangana through M/s. Xlant Infra (Hyderabad)",
        capacity: "2 Nos. of 20 kg/hr and 2 Nos. of 10 kg/hr chlorination system",
        year: "2017",
      },
      {
        serial: 95,
        client: "130 MLD WTP in Adilabad, Telangana Rural Water Supply through M/s. Eco Protection Engineers Pvt. Ltd., Chennai",
        capacity: "2 Nos. of 30 kg/hr and 2 Nos. of 15 kg/hr Chlorination system",
        year: "2017",
      },
      {
        serial: 96,
        client: "90 MLD WTP at Medak, Telangana Rural Water Supply through M/s. Eco Protection Engineers Pvt. Ltd., Chennai.",
        capacity: "2 Nos. of 25 kg/hr and 2 Nos. of 10 kg/hr Chlorination system",
        year: "2017",
      },
      {
        serial: 97,
        client: "410 MLD WTP Ph-III, HMWSSB, Kodandapur, Hyderabad through M/s Ramky - SMC JV",
        capacity: "4 Nos. of 60 kg/hr pre chlorination and 2 Nos. 20 kg/hr post chlorination system",
        year: "2016",
      },
      {
        serial: 98,
        client: "100 MLD WTP at Salaulim, PWD, Goa through M/s. Geo Miller & Co. Pvt. Ltd.",
        capacity: "4 Nos. of 20 kg/hr and 2 Nos. of 10 kg/hr Chlorination system with Leak Absorption system.",
        year: "2014",
      },
      {
        serial: 99,
        client: "70 MLD WTP at Ratangarh Sujangarh, PHED, Rajasthan through M/s. NCC Ltd., Hyderabad.",
        capacity: "4 Nos. of 20 kg/hr for pre and 2 Nos. of 10 kg/hr pre Chlorination system",
        year: "2014",
      },
      {
        serial: 100,
        client: "16 MLD STP at Jagron, Ludhana, PWSSB, Punjab through M/s. Gondwana Engineers Pvt. Ltd.",
        capacity: "2 Nos. of 5 kg/hr Chlorination system",
        year: "2014",
      },
      {
        serial: 101,
        client: "140 MLD WTP at KMDA, Madhyamgarh, Bengal through M/s. VA Tech Wabag Limited, Chennai",
        capacity: "2 Nos. of 25 kg/hr and 2 Nos. of 10 kg/hr Chlorination system",
        year: "2014",
      },
      {
        serial: 102,
        client: "Uluberia WTP, Kolkata through M/s. GB Construction, Kolkata",
        capacity: "2 Nos. of 10 kg/hr Chlorination system",
        year: "2014",
      },
      {
        serial: 103,
        client: "IOCL Paradip Refinery WTP Project, Orissa - through Clear Water Ltd",
        capacity: "5 Nos. 10 kg/hr Chlorination System",
        year: "2014",
      },
      {
        serial: 104,
        client: "M/s. GDC Ltd., New Delhi (Proj. Goa)",
        capacity: "2 Nos. of 20 Kg/hr Chlorination System.",
        year: "2013",
      },
      {
        serial: 105,
        client: "M/S. JUSCO - Garden Reach Water Works",
        capacity: "2 Nos. of 10 kg & 2 Nos. of 20 kg/hr Chloriantion system.",
        year: "2013",
      },
      {
        serial: 106,
        client: "M/s. Gondwana Engineers (Proj. Bhilai)",
        capacity: "2 Nos. of 10 Kg/hr Chlorination System",
        year: "2011",
      },
      {
        serial: 107,
        client: "M/s. Gharpure Engg. & Const. Co. (30 MLD at Ghansoli)",
        capacity: "2 Nos. of 4 kg.hr Chlorination system",
        year: "2010",
      },
      {
        serial: 108,
        client: "M/s. Ramky Infrastructure Ltd. (Proj. 125 MLD Madurai)",
        capacity: "2 Nos. of 30 kg/hr Chlorination system",
        year: "2010",
      },
      {
        serial: 109,
        client: "M/s. Ramky Infrastructure Ltd. (Proj. 125 MLD Madurai) (Repeat Order)",
        capacity: "2 Nos. of 30 kg/hr Chlorination system",
        year: "2010",
      },
      {
        serial: 110,
        client: "M/s. VA Tech Wabag Ltd., Chenna (Delhi Jal Board-Keshopur, Delhi)",
        capacity: "2 Nos. of 25 kg/hr Chlorination system.",
        year: "2009",
      },
      {
        serial: 111,
        client: "M/s. SMS Parayavaran Pvt. Ltd, (48.5 MLD WTP at Nashik)",
        capacity: "6 Nos of 10 kg/hr chloriantion system",
        year: "2009",
      },
      {
        serial: 112,
        client: "M/s. IOCL, Assam",
        capacity: "2 Nos. of 10 kg/hr Chlorination system",
        year: "2009",
      },
      {
        serial: 113,
        client: "M/s. IOCL, Mathura",
        capacity: "2 Nos. of 10 kg/hr Chlorination system",
        year: "2009",
      },
      {
        serial: 114,
        client: "M/s. Gharpure Engg. & Const. Co. (70 MLD at Coimbatore)",
        capacity: "2 Nos. of 15 Kg/hr CW Chlorination System",
        year: "2009",
      },
      {
        serial: 115,
        client: "IOCL Mathura - Thr ION Exchange (I) Ltd.",
        capacity: "3 Nos. of 10 kg/hr Chlorination system",
        year: "2009",
      },
      {
        serial: 116,
        client: "Nagarjuna Construction",
        capacity: "2 Nos. of 40 kg/hr, 2 Nos. of 20 kg/hr and Leak Absorption system.",
        year: "2008",
      },
      {
        serial: 117,
        client: "M/s. Electro Steel Casting Ltd., Calcutta",
        capacity: "6 Nos. of 500 gams/hr Chloriantion system",
        year: "2008",
      },
      {
        serial: 118,
        client: "M/s.Visakhapatnam Municipal Corpn (Thr. Batliboi Environmental Engg. Ltd.)",
        capacity: "2 Nos of 40 kg/hr Chlorination system",
        year: "2007",
      },
      {
        serial: 119,
        client: "M/s.Geomiller & Co. Pvt. Ltd. New Delhi( Hyderabad Metro) (Repeat order)",
        capacity: "2 Nos. of 60 kg/hr and 2 Nos. of 20 kg/h Vacuum Type Chlorination system.",
        year: "2006",
      },
      {
        serial: 120,
        client: "M/s. Bongaigaon Refinery & Petrochemicals Ltd, Assam",
        capacity: "2 Nos of 10 Kg/hr Vacuum type chlorination system.",
        year: "2006",
      },
      {
        serial: 121,
        client: "M/s. Linemann Halflow (India) Ltd, New Delhi.",
        capacity: "150kg/hr Chlorinator with 150kg/hr Vaporizer",
        year: "2006",
      },
      {
        serial: 122,
        client: "M/s. Clear Water Limited, New Delhi (RVUN-GIRAL)",
        capacity: "2 Nos of 5kg/hr Tonner Mounted Chlorination System.",
        year: "2006",
      },
      {
        serial: 123,
        client: "M/s. Lahoty Builders, Rajasthan.",
        capacity: "4 Nos of 5 Kg/hr Vacuum type chlorination system.",
        year: "2005",
      },
      {
        serial: 124,
        client: "M/s. Vishnu Prakash R Pungalia, Jodhpur (Devli Job)",
        capacity: "4 Nos of 2 kg/hr Gravity Feed Chlorination system",
        year: "2005",
      },
      {
        serial: 125,
        client: "M/s. Vishnu Prakash R Pungalia, Jodhpur (Devli Job)",
        capacity: "5 Nos of 2 Kg/hr Vacuum type chlorination system.",
        year: "2005",
      },
      {
        serial: 126,
        client: "ION Exchange (I) Pvt Ltd, Mumbai (Mandideep job)",
        capacity: "2 Nos of 25 Kg/hr Vacuum type chlorination system.",
        year: "2005",
      },
      {
        serial: 127,
        client: "ION Exchange (I) Pvt Ltd, Mumbai (CPCL- job)",
        capacity: "1 No of 2 kg/hr Gravity Feed Chlorination system",
        year: "2005",
      },
      {
        serial: 128,
        client: "M/s. Paramount Ltd, Gujarat (Mahad-job)",
        capacity: "2 Nos of 30 Kg/hr Vacuum type chlorination system.",
        year: "2005",
      },
      {
        serial: 129,
        client: "M/s. Technocon Projects & Engineering, Delhi.",
        capacity: "1 No of 40 Kg/hr Vacuum type chlorination system.",
        year: "2005",
      },
      {
        serial: 130,
        client: "M/s. Enviro Consultants, Vellor.",
        capacity: "2 Nos of 50 Kg/hr Vacuum type chlorination system.",
        year: "2005",
      },
      {
        serial: 131,
        client: "M/s. Engineering Centre United Kingdon (Export)",
        capacity: "2 Nos of 5 Kg/hr Vacuum type chlorination system.",
        year: "2005",
      },
      {
        serial: 132,
        client: "M/s. Laxmi Construction, Hyderabad",
        capacity: "2 Nos of 20 Kg/hr Vacuum type chlorination system.",
        year: "2005",
      },
      {
        serial: 133,
        client: "M/s. S N Nandy Co, New Delhi.",
        capacity: "2 Nos of 7 Kg/hr Vacuum type chlorination system.",
        year: "2005",
      },
      {
        serial: 134,
        client: "M/s. Aquatreat Exim Pvt. Ltd., Mumbai (Export order for Iraq)",
        capacity: "22 Nos. of 10 kg/hr and 3 Nos. of 5 kg/hr Chlorination system.",
        year: "2004",
      },
      {
        serial: 135,
        client: "M/s. VA Tech Wabag Ltd., Chennai (180 MLD WTP at Vadakathu for CMW & SB, Chennai)",
        capacity: "2 Nos. of 25 kg/hr Chlorination system with auto change over device and 2 Nos. of 10 kg/hr Ammoniation system auto change over device.",
        year: "2004",
      },
      {
        serial: 136,
        client: "Indian Oil Corporation, Mathura",
        capacity: "3 Nos. of 10 kg/hr and 2 Nos. of 15 kg/hr Chlorination system.",
        year: "2004",
      },
      {
        serial: 137,
        client: "M/s. Gannon Dunkerly & Co., New Delhi (Bikaner)",
        capacity: "2 Nos. of 20 kg/hr and 2 Nos. of 7.5 kg/h Chlorination system.",
        year: "2004",
      },
      {
        serial: 138,
        client: "M/s. Gannon Dunkerly & Co., New Delhi (Kota)",
        capacity: "Chlorination system ranging from 2 Kgs/hr to 20 Kgs/hr.",
        year: "2004",
      },
      {
        serial: 139,
        client: "M/s. Hindustan Dorr-Oliver Ltd, Mumbai.",
        capacity: "2 Nos of 30 Kg/hr Vacuum type chlorination system.",
        year: "2004",
      },
      {
        serial: 140,
        client: "M/s. Naveen Projects Ltd.,(WTP at Karamsana PHED at Rajasthan (Churu project)",
        capacity: "2 Nos. of 10 Kgs/hr and 2 Nos. of 5 Kgs/hr Chlorination system",
        year: "2004",
      },
      {
        serial: 141,
        client: "M/s.Geomiller & Co. Pvt. Ltd. (205, MLD WTP at Kodandapur (HMWSSB), Hyderabad)",
        capacity: "2Nos. Of 60 kgs/hr Pre-Chlorination system with Evaporator & accessories & 2Nos. of 20 kg/hr post chlorination system.",
        year: "2002",
      },
      {
        serial: 142,
        client: "M/s. Exim Trade Link, New Delhi (Export for Iraq for Department of Water & Sewerage)",
        capacity: "60 Nos. of 500 gms/hr, 50 Nos. of 1 kg/hr, 90 Nos. of 2 kg/hr, 50 Nos. of 3 kg/hr, 40 Nos. of 5 kg/hr, 40 Nos. of 6 kg/hr, 40 Nos. of 8 kg/hr, 40 Nos. of 10 kg/hr, 20 Nos. of 12 kg/hr and 20 Nos. of 20 kg/hr Chlorination system.",
        year: "2002",
      },
      {
        serial: 143,
        client: "Public Health Engineering Dept.(64 MLD WTP at Akelgarh, Kota (Raj.)",
        capacity: "2 Nos. of 12 Kg/hr & 2 Nos. of 12 Kg.hr Chlorination system.",
        year: "1999",
      },
      {
        serial: 144,
        client: "M/s. Geo Miller & Co.Ltd. (MWSSB, Akola WTP)",
        capacity: "4 Nos. of 5 Kg/hr Chlorination System.",
        year: "1998",
      },
      {
        serial: 145,
        client: "M/s. Geo Miller & Co. Ltd. (60 MLD WTP at Jodhpur PHED (Raj.)",
        capacity: "6 Nos. 6 Kg/hr Chlorination System.",
        year: "1998",
      },
      {
        serial: 146,
        client: "M/s. Hindustan Dorr Oliver Ltd. (IOCL Panipat Refinery)",
        capacity: "2 Nos. of 20 Kg/hr Chlorination System.",
        year: "1998",
      },
      {
        serial: 147,
        client: "M/s.Geo Miller & Co. Ltd. (Kurihod project)",
        capacity: "4 Nos. of 2.4 Kgs/hr Chlorination System.",
        year: "1998",
      },
      {
        serial: 148,
        client: "M/s.Geo Miller & Co. Ltd. (WTP at Bhaghera)",
        capacity: "6 Nos. of 6 Kgs/hr Chlorination System",
        year: "1998",
      },
      {
        serial: 149,
        client: "M/s. OM Construction Co (New Delhi 27.4P for PHED at Bhilwara.)",
        capacity: "4 Nos. of 6 kg/hr Chlorination system",
        year: "1997",
      },
      {
        serial: 150,
        client: "M/s. SMS Parayavaran Pvt. Ltd, MWSSB, Maharashtra",
        capacity: "4 Nos. of 7 Kg/hr Chlorination System.",
        year: "1997",
      },
      {
        serial: 151,
        client: "M/s. Geo Miller & Co.Ltd. (U P Jal Nigam)",
        capacity: "2 Nos of 10 Kg/hr Chlorination System.",
        year: "1997",
      },
      {
        serial: 152,
        client: "M/s. Geo Miller & Co.Ltd. (MWSSB, Satna WTP)",
        capacity: "2 Nos. of 5 Kg/hr Chlorination System.",
        year: "1997",
      },
      {
        serial: 153,
        client: "M/s.Triveni Engineering Works Ltd.",
        capacity: "3 Nos. of 24 Kg/hr and 2 Nos. of 18 Kg/hr Chlorination system.",
        year: "1997",
      },
      {
        serial: 154,
        client: "M/s. U.P. Jal Nigam, Agra.",
        capacity: "8 Nos. of 5 Kg/hr, 2 Nos. of 2 Kg/hr & 1 No. of 10 Kg/hr Chlorination system.",
        year: "1997",
      },
      {
        serial: 155,
        client: "M/s. Emtech Engineers, Madras",
        capacity: "2 Nos. of 2 Kg/hr Chlorinator System.",
        year: "1997",
      },
      {
        serial: 156,
        client: "M/s.Biyani Builders & Engineers",
        capacity: "2 x 1Kg/hr and 2 x 250 gm/hr",
        year: "1996",
      },
      {
        serial: 157,
        client: "M/s. Clear Water Limited., MWSSB, Vasai Virar WTP",
        capacity: "2 Nos. of 6 Kg/hr Chlorination System.",
        year: "1995",
      },
      {
        serial: 158,
        client: "M/s. Candy Filters (I) Limited.",
        capacity: "4 Nos. of 2 Kg/hr & 4 Nos. of 250 gm/hr Chlorination system.",
        year: "1995",
      },
      {
        serial: 159,
        client: "M/s. Engineers Guild, Calcutta",
        capacity: "3 Nos. of 2 Kg/hr and 2 Nos. of 1 kg/hr Chlorinaton system",
        year: "1995",
      },
    ],
  },
] as const;

export const thermalPowerClientSections = [
  {
    id: "thermal-power-plant-chlorination",
    title: "Thermal Power Plant Chlorination",
    entries: [
      {
        serial: 1,
        client: "UPRVUNL,2X660MW-ObraThermalPowerExtensionProject(Through M/s.DoosanPower System India Pvt. Ltd. / M/s. ION Exchange (India) Ltd. (Consultant - NTPC/DCPL) (Main Contractor : Doosan)",
        capacity: "5Nos.of200kg/hrCWChlorinationsystemwithLeakAbsorptionsystem,3Nosof12kg/hr RWChlorinationsystem,2Nos.of200gms/hrPWChlorinationsystemandmandatoryspares for all.",
        year: "2025",
      },
      {
        serial: 2,
        client: "UPRVUNL,2X660MW-JawaharpurSuperThermalPowerPlant(Through M/s.DoosanPower System India Pvt. Ltd. / M/s. ION Exchange (India) Ltd. (Consultant - NTPC/DCPL.) (Main Contractor : Doosan)",
        capacity: "3Nos.of180kg/hrCWChlorinationsystemwithLeakAbsorptionsystem,2Nos.of20kg/hr for RW Chlorination, 2 Nos. of 250 gms/hr for PW Chlorination and mandatory spares for all.",
        year: "2025",
      },
      {
        serial: 3,
        client: "2x660 MW Maitree STPP Bangladesh (through Ion Exchange-BHEL) (Main Contractor : BHEL)",
        capacity: "3x200 kg/hr CW Chlorination System with Leak Absorption, 2x100 kg/hr River Water Chlorination with Leak Absorption and 2x20 kg/hr PT Chlorination.",
        year: "2024",
      },
      {
        serial: 4,
        client: "UPRVUNL, 2X660 MWHarduaganjTPS(ThroughToshiba / DriplexWater EngineeringLtd.). (Consultant - Desein) (Main Contractor : Toshiba)",
        capacity: "2Nos.of210kg/hrChlorinationsystemwithLeakAbsorptionsystem,2Nos.of10kg/hrfor RW Chlorination, 2 Nos. of 1 kg/hr for PW Chlorination and mandatory spares for all.",
        year: "2022",
      },
      {
        serial: 5,
        client: "Chandrapur Thermal Power Plant, 2x300 MW (Through M/s. Dhariwal Infrastructure Limited",
        capacity: "2Nos.of20kg/hrChlorinationsystemwithChlorineLeakAbsorptionsystemandmandatory spares.",
        year: "2019",
      },
      {
        serial: 6,
        client: "Chhabra Thermal Power Station (Through -Indure Pvt. Ltd.) (Consultant - TCE)",
        capacity: "2 Nos. of 110 kg/hr CW Chlorination system with Leak absorption system.",
        year: "2015",
      },
      {
        serial: 7,
        client: "MAHAGENCO-2x500 MW Chandrapur TPS (through M/s. BGR Energy Systems Ltd.), Chennai",
        capacity: "3 Nos.of 150 kg/hrwithleakabsorption system and 2 Nos.of 200 gms/hr PWChlorination system.",
        year: "2015",
      },
      {
        serial: 8,
        client: "APGENCO - 1x210 MW Rayalseem Thermal Power Plant Phase-III., Andhra Pradesh",
        capacity: "2 Nos. of 80 Kg/hr Chlorination system with Leak Absorption system.",
        year: "2013",
      },
      {
        serial: 9,
        client: "TANGEDCO - 2x600 MW Mettur Thermal Power Plant (through M/s. BGR Energy System Ltd.)",
        capacity: "2 nos. of 200 kg/hr CW Chlorination system with Leak Absorption system.",
        year: "2013",
      },
      {
        serial: 10,
        client: "MAHAGENCO 2x500 MW Bhusawal TPS (Through M/s. ION Exchange (India Ltd.), Mumbai)",
        capacity: "2 Nos. of 10 kg/hr Chlorination system",
        year: "2012",
      },
      {
        serial: 11,
        client: "MAHAGENCO 2x500 MW Bhusawal TPS (Through M/s. Tata Projects Ltd.)",
        capacity: "3 Nos. of 150 kg/hr CW Chlorination system with Leak Absorption system",
        year: "2012",
      },
      {
        serial: 12,
        client: "RVUNL, 195 MW Stage-V, Kota TPS (Through M/s. TATA Projects)",
        capacity: "2 Nos. of 80 Kg/hr Chlorination system with Leak Absorption system.",
        year: "2010",
      },
      {
        serial: 13,
        client: "NTPC, Kahalgaon Super Thermal Power Plant",
        capacity: "Chlorine Leak Absorption System.",
        year: "2009",
      },
      {
        serial: 14,
        client: "Lanco Amarkantak Thermal Power Station 2x300 MW (Through M/s. Lanco Infrastructure Limited)",
        capacity: "3Nos.of200kg/hrCWChlorinationsystemwithLeakAbsorptionSystem,2Nos.of15kg/hr RW Chlorination system and 2 Nos. of 250 gms/hr PW Chloriantion system.",
        year: "2008",
      },
      {
        serial: 15,
        client: "Vijaywada Thermal Power Station",
        capacity: "2 Nos. of 30 kg/hr Chlorination system",
        year: "2008",
      },
      {
        serial: 16,
        client: "RRVUNL, 1x125 MW Giral Lignite TPS (Through M/s. TATA Projects Limited)",
        capacity: "1 No. of 40 kg/hr Chlorination system",
        year: "2008",
      },
      {
        serial: 17,
        client: "RRVUNL, 1x125 MW Giral Lignite TPS Barmer",
        capacity: "2 Nos. of 40 kg/hr Chlorination system with Leak Absorption system",
        year: "2007",
      },
      {
        serial: 18,
        client: "RRVUNL,330 MW Combained Cycle Gas Power Project, Dholpur (Through GEA Energy System)",
        capacity: "2 Nos. of 120 kg/hr, 2 Nos. of 4 kg with Leak Absorption system.",
        year: "2007",
      },
      {
        serial: 19,
        client: "APGENCO- RTPP (Through M/s. Batliboi )",
        capacity: "2 Nos. of 20 kg/hr Chlorination system",
        year: "2007",
      },
      {
        serial: 20,
        client: "Haryana Thermal Power station, Faridabad",
        capacity: "1 No. of 20 Kg/hr chlorination System",
        year: "2004",
      },
      {
        serial: 21,
        client: "Haryana Thermal Power station, Faridabad",
        capacity: "1 No. of 20 Kg/hr chlorination System",
        year: "2003",
      },
      {
        serial: 22,
        client: "A.P.State Electricity Boad (APGENCO) Project 4x60 MW KTPS-A Kothagudam A.P",
        capacity: "2x50Kg/hr. CW Chlorination system with Leak Absorption System",
        year: "2003",
      },
      {
        serial: 23,
        client: "BSESLtd.230MWCombinedCyclePowerProject,Samalkot,AndhraPradesh(ReliancePower Limited)",
        capacity: "2 Nos. of 60Kg/hr. CW Chlorination System with Leak Absorption System",
        year: "2003",
      },
      {
        serial: 24,
        client: "Neyveli Lignite Corporation Ltd. Thermal Power Station Expansion I (Consultant : MECON)",
        capacity: "3 Nos. of 100Kg/hr Chlorination, Leak Absorption and Chemical Dosing System.",
        year: "2002",
      },
      {
        serial: 25,
        client: "Andhra Pradesh State Electricity Board Kothagudum 2x 250 MW TPS- V through M/s. Clear Water Limited, New Delhi (Consultant : Desein Ltd.)",
        capacity: "3 Nos. of 120Kg/hr Chlorination Systems.",
        year: "2000",
      },
      {
        serial: 26,
        client: "Bechtel International Inc., Enron Power Project Dabhol - Phase II (Repeat Order)",
        capacity: "Chlorine Leak Absorption System.",
        year: "2000",
      },
      {
        serial: 27,
        client: "M/s. BSES Kerala Power Ltd. Kochi Kerala (Consultant: Fichtner Consulting Engineers (India) Pvt. Ltd.)",
        capacity: "2 Nos. of 15 Kg/hr CW Chlorination System",
        year: "2000",
      },
      {
        serial: 28,
        client: "Rajasthan State Electricity Board, Suratgarh T.P.S (Consultant : Development Consultant.)",
        capacity: "2 Nos. of 750Gms/hr & 2 Nos. of 75 gms/hr Chlorination System",
        year: "1998",
      },
      {
        serial: 29,
        client: "NTPC Badarpur BTPS (Through Enviral Projects Pvt. Ltd.)",
        capacity: "1 No. of 1 Kg/hr Chlorination System.",
        year: "1998",
      },
      {
        serial: 30,
        client: "Bechtel International Inc., Enron Power Project.",
        capacity: "1000 Kg/hr Chlorine Leak Neutralization System.",
        year: "1998",
      },
      {
        serial: 31,
        client: "Rajasthan Atomic Power Project",
        capacity: "2 Nos. of 2 Kg/hr Chlorination System.",
        year: "1997",
      },
      {
        serial: 32,
        client: "Punjab State Electricity Board, Guru Nanakdev T.P.S (Consultant : Tata Consulting Engineer)",
        capacity: "2 Nos. of 5 Kg/hr Chlorination System.",
        year: "1997",
      },
      {
        serial: 33,
        client: "National Thermal Power Corp,NTPC Auryia Gas Power Project",
        capacity: "Valves & Chlorination systems accesories",
        year: "1996",
      },
      {
        serial: 34,
        client: "APSEB, RTPP T P S (Through Clear Water / Desein Ltd.)",
        capacity: "2 Nos. of 10 Kg/hr Chlorination System.",
        year: "1995",
      },
    ],
  },
  {
    id: "peper-mill-chlorination-for-bleach-liquor",
    title: "PEPER MILL CHLORINATION FOR BLEACH LIQUOR",
    entries: [
      {
        serial: 1,
        client: "M/S. Star Paper Mills Ltd.",
        capacity: "1 No. Of 100 Kg/hr Evaporator System.",
        year: "1988",
      },
      {
        serial: 2,
        client: "M/s. Shiva Paper Mill Limited",
        capacity: "2 Nos. of 200 Kg/hr Evaporator System.",
        year: "1989",
      },
      {
        serial: 3,
        client: "M/s.Shreeram Rayons Ltd.",
        capacity: "2 Nos. of 200 Kg/hr Evaporator System.",
        year: "1993",
      },
      {
        serial: 4,
        client: "M/s. Shiva Paper Mill Limited",
        capacity: "1 Nos. of 500 Kg/hr Evaporator System. (Repeat order after 6 Years.)",
        year: "1995",
      },
      {
        serial: 5,
        client: "M/s. Mohit Paper Mill Limited.",
        capacity: "1 No. of 200 Kg/hr Evaporator System.",
        year: "1995",
      },
      {
        serial: 6,
        client: "M/s. Hindustan Dorr Oliver Ltd. ( World Bank Export Order)",
        capacity: "1 No. of 300 Kg/hr & 1 No. 200 Kg/hr Evaporator System.",
        year: "1996",
      },
      {
        serial: 7,
        client: "M/s. Gandhar Petrochemicals Ltd.",
        capacity: "1 No. of 1000 kg/hr Steam Heated Vaporizer",
        year: "2007",
      },
    ],
  },
  {
    id: "chlorine-leak-absorption-system",
    title: "CHLORINE LEAK ABSORPTION SYSTEM",
    entries: [
      {
        serial: 1,
        client: "M/s. A P Paper Mills Limited",
        capacity: "1000 kg Chlorine Gas Leak Asorption system",
        year: "1992",
      },
      {
        serial: 2,
        client: "M/s. Sirpur Paper Mills Ltd.",
        capacity: "Chlorine Gas Leak Asorption system",
        year: "1994",
      },
      {
        serial: 3,
        client: "M/s. Bachtel International Inc., Enron Power Project, Dabhol, Phase-I.",
        capacity: "1000 kg Chlorine Leak Neutralization system",
        year: "1998",
      },
      {
        serial: 4,
        client: "M/s. Bachtel International Inc., Enron Power Project, Dabhol, Phase-II (Repeat Order).",
        capacity: "1000 kg Chlorine Leak Neutralization system",
        year: "2000",
      },
      {
        serial: 5,
        client: "M/s. Neyveli Lignite Corpn Ltd Thermal Power station Expansion-1",
        capacity: "1000 kg /hr Chlorine Gas Leak Asorption system",
        year: "2002",
      },
      {
        serial: 6,
        client: "Andhra Pradesh State Electricity Board -Kothagudum TPS- A",
        capacity: "1000 kg /hr Chlorine Gas Leak Asorption system",
        year: "2003",
      },
      {
        serial: 7,
        client: "M/s. Reliance Energy Limited- Samalkot",
        capacity: "1000 kg /hr Chlorine Gas Leak Asorption system",
        year: "2003",
      },
      {
        serial: 8,
        client: "M/s. Pranchie Nirman Pvt. Ltd",
        capacity: "1000 kg /hr Chlorine Gas Leak Asorption system",
        year: "2003",
      },
      {
        serial: 9,
        client: "M/s. Jindal Vijaynagar Limited- Bellary",
        capacity: "1000 kg /hr Chlorine Gas Leak Asorption system",
        year: "2004",
      },
      {
        serial: 10,
        client: "M/s. Jindal steel & Power Ltd - Raigarh",
        capacity: "1000 kg /hr Chlorine Gas Leak Asorption system",
        year: "2004",
      },
      {
        serial: 11,
        client: "IB Thermal Power Station - Orissa",
        capacity: "1000 kg /hr Chlorine Gas Leak Asorption system",
        year: "2005",
      },
      {
        serial: 12,
        client: "M/s. Toshcon Jesco",
        capacity: "Chlorine Leak Absorption system",
        year: "2008",
      },
      {
        serial: 13,
        client: "M/s. Electro Steel Casting Ltd., Calcutta",
        capacity: "Chlorine Leak Absorption system",
        year: "2010",
      },
    ],
  },
  {
    id: "fertilizer-petro-chemical",
    title: "FERTILIZER & PETRO CHEMICAL",
    entries: [
      {
        serial: 1,
        client: "M/s. Neyveli Lignite Corpn Ltd (Fertilizer Cooling Water Plant)",
        capacity: "1 x 20Kg/hr Chlorination system",
        year: "1995",
      },
      {
        serial: 2,
        client: "M/s. Neyveli Lignite Corpn Ltd (Fertilizer Cooling Water Plant)",
        capacity: "1 x 20 kg/hr Chlorination System",
        year: "1996",
      },
    ],
  },
  {
    id: "chemical-pharmaceutical-industry",
    title: "CHEMICAL & PHARMACEUTICAL INDUSTRY",
    entries: [
      {
        serial: 1,
        client: "M/s. Ranbaxy Laboratories Ltd.",
        capacity: "1 x100 Kg/hr Evaporator System.",
        year: "1992",
      },
      {
        serial: 2,
        client: "M/s. H.P.L Chemicals Limited.",
        capacity: "2 x200Kg/hr Evaporator System.",
        year: "1993",
      },
      {
        serial: 3,
        client: "M/s. High Polymers Ltd.",
        capacity: "2 x700Kg/hr Evaporator System.",
        year: "1996",
      },
      {
        serial: 4,
        client: "M/s. Demaco Polymers Ltd.",
        capacity: "1 x1000 Kg/hr Evaporator System.",
        year: "2000",
      },
      {
        serial: 5,
        client: "M/s. Sharma Brothers",
        capacity: "1 x500 Kg/hr Evaporator System.",
        year: "2002",
      },
      {
        serial: 5,
        client: "M/s. High Polymers Ltd.",
        capacity: "1 x700 Kg/hr Evaporator System.",
        year: "2004",
      },
      {
        serial: 6,
        client: "M/s. Taiyo Nippon Sanso India Pvt Ltd, Hyderabad",
        capacity: "1 x 210 kg/hr Evaporator System",
        year: "2019",
      },
    ],
  },
  {
    id: "steam-heated-evaporator",
    title: "STEAM HEATED EVAPORATOR",
    entries: [
      {
        serial: 1,
        client: "IICP, Egypt (Export)",
        capacity: "3 Nos. of Steam Heated Evaporator",
        year: "2005",
      },
      {
        serial: 2,
        client: "Ruchira Paper Limited",
        capacity: "2 Nos. of 200 kg/hr Steam Heated Vaporizer",
        year: "2008",
      },
      {
        serial: 3,
        client: "M/s. Jubilant Organosis",
        capacity: "1 No. of 150 kg/hr Steam Heated Evaporator",
        year: "2008",
      },
      {
        serial: 4,
        client: "M/s. Jubilant Organosis (Repeat Order)",
        capacity: "1 No. of 150 kg/hr Steam Heated Evaporator",
        year: "2009",
      },
    ],
  },
] as const;

export const clientListCatalogs = [
  {
    id: "wtp-stp",
    title: "WTP & STP Chlorination",
    description:
      "Water treatment plant and sewage treatment chlorination projects across municipal, industrial, and rural water supply schemes.",
    pdf: "/product/Client list for WTP & STP Chlorination System.pdf",
    sections: wtpStpClientSections,
  },
  {
    id: "thermal-power",
    title: "Thermal Power Plant Chlorination",
    description:
      "Cooling water, river water, and potable water chlorination systems for thermal power stations, plus allied industrial applications.",
    pdf: "/product/Client list for Thermal Power Plant Chlorination System.pdf",
    sections: thermalPowerClientSections,
  },
] as const satisfies readonly ClientListCatalog[];
